### ISSUE TITLE
Admin UI issues

### ISSUE THREAD

**Issue by alexgleason** [ProjectTIER/projecttier.org#3] opened 2018-02-05 00:53 UTC
This was previously using [wagtailatomicadmin](https://github.com/alexgleason/wagtailatomicadmin) but the latest version of Wagtail broke it beyond the point of repair. Unfortunately the default Wagtail styles are also pretty broken:

![screenshot from 2018-02-04 19 51 45](https://user-images.githubusercontent.com/3639540/35784384-dd602c72-09e4-11e8-9f9f-a22f5ff8eef6.png)

I'll need to either update wagtailatomicadmin or send a PR to Wagtail itself. I'm feeling the latter will be a better option at this point.

**Comment by marykatefain** [comment] 2018-09-19 18:35
This must have been fixed by an update somewhere down the line, I'm unable to reproduce this bug. Closing.

**Closed by marykatefain** 2018-09-19 18:35 UTC
